title: BITwiki
baseurl: ""          # root build for GitHub‑Pages
markdown: kramdown
theme: null
collections:
  research:
    output: true
permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: research
      toc: true
plugins: []          # stay on GH‑Pages safelist
exclude: [node_modules, public]
